### PR TITLE
extended generate_mesh() interface to optionally keep the gmsh-generated mesh file

### PR DESCRIPTION
**Pull request by fpreiss**
This addition allows to avoid using the meshio interface if the gmsh generated mesh suffices.

### CODE REVIEW

**Comment by nschloe** [comment]
Can't you just write it to a file after the deed is done? (Not a fan of adding more options.)

**Comment by fpreiss** [comment]
Sure I can understand, though I'd argue there are benefits in using the suggested extension with
```python

import pygmsh

geom = pygmsh.built_in.Geometry()
…
…
mesh = pygmsh.generate_mesh(geom,msh_filename='mymesh.msh')
```
over
```python
import meshio

import pygmsh

geom = pygmsh.built_in.Geometry()
…
…
mesh = pygmsh.generate_mesh(geom)
meshio.write("mymesh.msh", mesh)
```
In my case I had to deal with a particular unhandly mesh that took gmsh about 3hours to generate and broke with meshio (probably worth some further investigation if I find the time). As the current `generate_mesh()` implementation deletes the generated mesh, I had to give the `.geo` file another 3hours. I believe the additions I made are fairly consistent with the `geo_filename` option and I imagine they could be helpful on other occasions.
Ultimatively its your decision and I suppose there are certain benefits to both approaches.

with best regards,
fpreiss

**Comment by nschloe** [comment]
> 3 hours to generate

Whoaw!

>  I had to give the .geo file another 3 hours. 

Super frustrating. :frowning_face: 

> I believe the additions I made are fairly consistent with the geo_filename option and I imagine they could be helpful on other occasions.

Yeah, I was actually planning on removing `geo_filename` since you can easily get the info from the geo object itself.

I was going to say let's merge it, and I'll remove it again when I remove geo_filename. (Might take a while.) But I can't do it with `bincode`. That option is really confusing, and _only_ concerns the msh file _and_ ascii files only have disadvantages compared to binary ones, so it's actually dangerous to expose that. If you remove it, I'll merge.

**Comment by fpreiss** [comment]
In my particular case I had to add the `bincode` as an option for further exporting to OpenFOAM with the `gmsh2ToFoam` conversion tool (which only accepts ASCII) - that might be a rather niche usecase though. Thanks for your feedback, I'll update asap.

**Pull request merged**
