### PR TITLE
Adding function to recombine mesh for generation of quad elements

### PR DESCRIPTION
**Pull request by awa5114**
Adding function and corresponding test. It seems to work find but I eagerly await your feedback.

### CODE REVIEW

**Comment by nschloe** [comment]
Next time you can simply use `make format`; the test failures are okay.

**Comment by awa5114** [comment]
Allright, next time I will. Just out of curiosity, why are you OK with the test failures?

**Comment by nschloe** [comment]
The tests are redundant, circleci passes and that's fine. The gh-actions still have issues sometimes which were the failing ones.

**Comment by nschloe** [comment]
> Also how would you recommend incorporating this change into my anaconda environment?

No idea. Is pygmsh on anaconda cloud?

**Comment by nschloe** [comment]
Frankly I'd just use the raw code for now, and wait for a proper release to update your code.

**Comment by awa5114** [comment]
@nschloe  I just remembered theres a better way, namely navigating to the working directory of `pygmsh` repo under the conda environment of choice and running a:

`pip install .`

That dumps the HEAD revision of whatever is in the working directory to the anaconda environment currently active....

**Pull request merged**
