### PR TITLE
add discord badge

### PR DESCRIPTION
**Pull request by nschloe**

### CODE REVIEW

**Comment by Foadsf** [comment]
I'm not sure if it is only me, but the [Discord link/badge](https://discord.com/channels/818781969562599434/818781969562599438) doesn't work:

2021-03-18 08_42_54-Discord

But you are still highly welcomed to join the [#gmsh channel on Elmer's Discord](https://github.com/nschloe/pygmsh/issues/359).

**Comment by nschloe** [comment]
Does [this](https://discord.gg/BphXfpmb) work better?

**Comment by Foadsf** [comment]
just make sure your invitation link is permanent. the default ones are usually temporary

**Comment by nschloe** [comment]
Got that.

**Pull request merged**
