### PR TITLE
Fusion opencascade builtin

### PR DESCRIPTION
**Pull request by tryfon-mw**
This PR contains all changes (14 commits) that have been made by Multiwave. The inheritance of the built_in works for now in the sense that we can use booleans for the built_in geometries. But let s find an optimal way to get around this.
Let me know which changes to make to get this in shape.

Thanks

### CODE REVIEW

**Comment by nschloe** [comment]
There are so many different changes and so few comments in here that this PR has little chance getting merged. Could this be split up into smaller logical units? I see `volumes_inside`, separate `delete1` and `delete2` etc.

**Comment by tryfon-mw** [comment]
I agree, we should split this in a few commits at least. Let us work on this and PR in sections.

Tryfon Antonakakis
Co Founder & CEO

Multiwave Technologies AG
3 Chemin du Pré Fleuri
1228, Geneva
Switzerland
+41 (0) 76 46 12 023

**Comment by nschloe** [comment]
@tryfon-mw Can we close this one? (See the comment above.)

**Comment by nschloe** [comment]
Alright, so I guess we could cherry-pick from here, or just starting new PRs by copy-and-pasting the parts of the diff here.

**Pull request closed without merging**
