### PR TITLE
remove internal surface

### PR DESCRIPTION
**Pull request by capitalaslash**

### CODE REVIEW

**Comment by nschloe** [comment]
Ah, the test error occurs because of a new meshio version. Let me fix this.

**Comment by gdmcbain** [comment]
Ah, I didn't know about the `make_surface=True` option in `add_{circle,rectangle,polygon}`.  Thanks.  
   I think test/test_screw.py needs the same `make_surface=False` correction that test_layers.py received in 5076982.

**Comment by nschloe** [comment]
I'm wondering if the default should be `False`, after all. Or if we should force the user to manually create the surface from the outline.

**Comment by gdmcbain** [comment]
Oh, O. K., well that would work too.  Mathematicians sometimes like to distinguish circles from disks.  I'm not sure that I have an opinion.  The Gmsh .geo built-in syntax does make the distinction via `Line Loop`, but then the *raison d'être* of PyGmsh is not to follow that too slavishly.

**Comment by capitalaslash** [comment]
I would keep the default to `True`, after all the main use case should be creating disks and not creating holes.

**Pull request merged**
