### PR TITLE
Boolean operators

### PR DESCRIPTION
**Pull request by capitalaslash**
The remaining Boolean operator available in gmsh-3.

### CODE REVIEW

**Comment by nschloe** [comment]
Perhaps the three Boolean tests can be combined into one?

**Comment by nschloe** [comment]
Are still multiple tests?

**Comment by capitalaslash** [comment]
sorry, I don't get it.
I merged the 3 tests into a single test, that in fact runs 3 of the 4 new interfaces to increase code coverage.
Did you mean something different?

**Comment by nschloe** [comment]
I see two files:
```
test/examples/boolean_diff.py
test/examples/boolean_int.py
```

**Comment by capitalaslash** [comment]
sorry, forgot to remove them.

**Comment by nschloe** [comment]
To save some redundancy in the Boolean functions, you could use `*args, **kwargs` à la
```python
def op(operation, x, y):
    if operation == '+':
        return x + y
    assert operation == '*'
    return x * y


def add(*args, **kwargs):
    return op('+', *args, **kwargs)


def multiply(*args, **kwargs):
    return op('*', *args, **kwargs)


print(add(2, 3))
print(multiply(2, 3))
```

**Pull request merged**
