### PR TITLE
added tests for surface area computations

### PR DESCRIPTION
**Pull request by tryfon-mw**
Added a couple more boolean tests. 
Also added test for surface area of the fragments be it from geometrical elements or physical.

### CODE REVIEW

**Comment by tryfon-mw** [comment]
the error i read is missing keys in the cell_data dict coming out of the generate_mesh, namely physical and geometrical.

Does this have to do with meshio?

**Comment by nschloe** [comment]
Yeah sure, I mean, the msh file has to be read in somewhere. :)

**Comment by nschloe** [comment]
Tadaa!

**Comment by tryfon-mw** [comment]
Thanks for the tip ;)

**Pull request merged**
