### PR TITLE
Add optional flag to the definition of transfinite lines/surface.

### PR DESCRIPTION
**Pull request by anzil**
The intention of this is to allow the provision of options when defining transfinite items, e.g.
```
geom.set_transfinite_lines([l0, l2], size=10, flag="Using Bump 0.1")
geom.set_transfinite_surface(mysurf, size=None, flag="Alternate")
```

### CODE REVIEW

**Comment by nschloe** [comment]
Ping me once the tests are passing.

**Comment by anzil** [comment]
Checks are passing now. Please review the suggested modifications. Thanks!

**Comment by nschloe** [comment]
The name `flag` is too generic. Or is it called that in gmsh? Can't find documentation on this.

Also, you're repeating too much code. Better would be to do something like
```python
    def set_transfinite_lines(self, lines, size, flag=None):
         code = "Transfinite Line {{{0}}} = {1}".format(", ".join([l.id for l in lines]), size)
         if flag is not None
             code += flag
         self._GMSH_CODE.append(code + ";")
```

**Comment by anzil** [comment]
Thanks for the feedback, @nschloe . I have updated the code and changed the name of the optional parameter to `optional_argument`. This is how it is called in the gmsh documentation (see [gmsh docs](http://gmsh.info/doc/texinfo/gmsh.html#Structured-grids) and the transfinite items therein).

**Comment by nschloe** [comment]
Well, `optional_argument` isn't much clearer either. After reading the documentation, I would suggest to add two new arguments to to `Transfinite Line`, `progression` and `bump`, each defaulting to `None`. Then make sure that at most one of the two is not `None`, and append it to the code.

For the `Transfinite Surface`, I would suggest `orientation=None`.

This way, it'll be clearer for the user of pygmsh what is meant by the arguments. This is one of the advantages of pygmsh over gmsh.

**Comment by anzil** [comment]
I have now implemented the options in the suggested way. I agree that this way the user interface is much clearer.

**Comment by nschloe** [comment]
Looking good now. :+1:

**Pull request merged**
