### PR TITLE
Allow extra options (layers,recombine) for rotate-only extrude operation.

### PR DESCRIPTION
**Pull request by anzil**

### CODE REVIEW

**Comment by nschloe** [comment]
This needs more explanation. What is it good for, what does it do, what's possible with the PR that's impossible without?

**Comment by nschloe** [comment]
Also, note to self: Think about a different formatting system. Those brackets are getting out of hand. (Perhaps https://stackoverflow.com/a/40877821/353337)

**Comment by anzil** [comment]
Sure, here comes the explanation:

The `extrude` method of the `Geometry` class accepts the optional parameters `num_layers` and `recombine` which are supposed to result in appending the Gmsh options `Layers{}` and `Recombine` to the code. Gmsh accepts these two options for the extrude operations *translate-only*, *translate-and-rotate* and *rotate-only* (http://gmsh.info/doc/texinfo/gmsh.html#Extrusions).

In the current version of `extrude`, the treatment of the case *rotate-only* simply ignores the parameters `num_layers` and `recombine` if provided.

The proposed modifications to the `extrude` method fix this and ensure that in all cases the above mentioned optional parameters are correctly taken into account in the construction of `_GMSH_CODE`.

Example that works correctly only with the proposed PR:
```python
p0 = geom.add_point([1, 0, 0])
p1 = geom.add_point([3, 0, 0])
l0 = geom.add_line(p0, p1)
geom.set_transfinite_lines([l0], size=20, progression=1.2)
# create a sector by extrusion (extrude: rotate-only)
l1,s1,_ = geom.extrude(l0, point_on_axis=[0,0,0], rotation_axis=[0,0,1], angle='Pi/2', num_layers=10, recombine=True) # produces 10 layers of elements (quad)
```

**Comment by nschloe** [comment]
I get it now; this is actually a bug fix. Nicely done!

**Pull request merged**
